### ISSUE TITLE
Chapter 10 - ALGORITHM DESIGN TECHNIQUES

### ISSUE THREAD

**Issue by venkateshwaranL** [csebooks/ds-algorithms#43]
Chapter 10 is yours.
[CHAPTER 10  ALGORITHM DESIGN TECHNIQUES.pdf](https://github.com/csebooks/ds-algorithms/files/14107399/CHAPTER.10.ALGORITHM.DESIGN.TECHNIQUES.pdf)

**Comment by VIJAYWHAT** [comment]
10th chapter finished
